<a href="https://colab.research.google.com/github/kritikamandale/Python_is_a_language/blob/main/day1_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'a

In [3]:
len(dir(np))

532

In [4]:
pip install scikit-learn

In [5]:
import seaborn as sns

In [6]:
data = sns.load_dataset('titanic')

In [7]:
data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [9]:
data.sample(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
329,1,1,female,16.0,0,1,57.9792,C,First,woman,False,B,Cherbourg,yes,False
552,0,3,male,NaN,0,0,7.8292,Q,Third,man,True,NaN,Queenstown,no,True
799,0,3,female,30.0,1,1,24.1500,S,Third,woman,False,NaN,Southampton,no,False
199,0,2,female,24.0,0,0,13.0000,S,Second,woman,False,NaN,Southampton,no,True
171,0,3,male,4.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
275,1,1,female,63.0,1,0,77.9583,S,First,woman,False,D,Southampton,yes,False
149,0,2,male,42.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
530,1,2,female,2.0,1,1,26.0000,S,Second,child,False,NaN,Southampton,yes,False
669,1,1,female,NaN,1,0,52.0000,S,First,woman,False,C,Southampton,yes,False
641,1,1,female,24.0,0,0,69.3000,C,First,woman,False,B,Cherbourg,yes,True


In [10]:
data.drop("embarked", axis=1,inplace = True)

In [11]:
data.head()

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,Third,man,True,NaN,Southampton,no,True


In [12]:
data.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'class',
       'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone'],
      dtype='object')

In [13]:
data.drop(['who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone'],axis = 1,inplace=True)

In [14]:
data.head()

,survived,pclass,sex,age,sibsp,parch,fare,class
0,0,3,male,22.0,1,0,7.2500,Third
1,1,1,female,38.0,1,0,71.2833,First
2,1,3,female,26.0,0,0,7.9250,Third
3,1,1,female,35.0,1,0,53.1000,First
4,0,3,male,35.0,0,0,8.0500,Third


In [20]:
data.isna().sum()

,0
survived,0
pclass,0
sex,0
age,0
sibsp,0
parch,0
fare,0
class,0


In [21]:
data['age'].fillna(data['age'].mean(), inplace = True)

In [22]:
data.isna().sum()

,0
survived,0
pclass,0
sex,0
age,0
sibsp,0
parch,0
fare,0
class,0


In [23]:
data['age'] = data['age'].astype(int)

In [24]:
data['sex'].unique()

array(['male', 'female'], dtype=object)

In [25]:
data['pclass'].unique()

array([3, 1, 2])

In [26]:
data['survived'].unique()

array([0, 1])

In [27]:
data['sibsp'].unique()

array([1, 0, 3, 4, 2, 5, 8])

In [28]:
data['parch'].unique()

array([0, 1, 2, 5, 3, 4, 6])

In [29]:
data["age"].value_counts()

,count
age,
29,197
24,31
22,27
28,27
30,27
...,...
66,1
12,1
53,1


In [30]:
data["sex"].value_counts()

,count
sex,
male,577
female,314


In [31]:
data["survived"].value_counts()

,count
survived,
0,549
1,342


In [32]:
import pandas as pd

In [33]:
data_encoded = pd.get_dummies(columns=['sex'],data=data,dtype = int, drop_first = True)

In [34]:
data_encoded.head()

,survived,pclass,age,sibsp,parch,fare,class,sex_male
0,0,3,22,1,0,7.2500,Third,1
1,1,1,38,1,0,71.2833,First,0
2,1,3,26,0,0,7.9250,Third,0
3,1,1,35,1,0,53.1000,First,0
4,0,3,35,0,0,8.0500,Third,1


In [35]:
data_encoded.to_csv("titanic_cleaned.csv", index = False)